services:
  aiogram:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    tty: true
    restart: unless-stopped
    container_name: telegram-bot
    env_file: .env
    ports:
      - 9000:9000
    volumes:
      - .:/opt/telegram-bot:cached
    command: uv run python -m src.main
    develop:
      watch:
        - action: sync
          path: ./
          target: /opt/telegram-bot
          ignore:
            - .venv/
            - __pycache__/
            - .git/
            - .pytest_cache/
            - .mypy_cache/
            - .ruff_cache/
            - logs/
            - .env
            - .DS_Store

        - action: rebuild
          path: ./pyproject.toml
        
        - action: rebuild
          path: ./Dockerfile

networks:
  default:
    external: true
    name: telegram-network